AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'examples/**/*'
    - 'unimplemented_features/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
Metrics/LineLength:
  Max: 100
Style/GlobalVars:
  AllowedVariables: [$RSPEC_TEST]
