notifications:
  email: false
language: ruby
sudo: required
os:
  - osx
rvm:
  - ruby-2.2.2
  - ruby-2.3.0
  - ruby-2.5.0
addons:
  code_climate:
    repo_token: 60d9731d654527cb53aabc7db15bcde87d701ddb6b1cba8fc0da6aba16d00bb1
before_install:
  - brew update
  - brew install pdflib-lite
  - brew install gnuplot --with-png --with-jpeg --with-cairo --with-svg
  - ulimit -S -n 4096
  - gem update bundler
  - bundle install
install:
  - bundle exec rake install
script:
  - bundle exec rake spec
after_success:
  - bundle exec codeclimate-test-reporter
