notifications:
  email: false
language: ruby
rvm:
  - ruby-2.0
  - ruby-2.1.5
  - ruby-2.2.2
  - jruby-9.0.0.0.pre2
env:
  - JRUBY_OPTS="-Xcli.debug=true --debug"
addons:
  code_climate:
    repo_token: bbd2a5e077e4b62bd8ba21a74a2ba901defc43506812f6192efc6b2a25c20d49
before_install:
  - sudo add-apt-repository "deb http://cz.archive.ubuntu.com/ubuntu vivid main universe"
  - sudo apt-get update -q
  - sudo rm -rf /etc/dpkg/dpkg.cfg.d/multiarch
  - sudo apt-get install gnuplot5
  - bundle install
install:
  - bundle exec rake install
script:
  - bundle exec rake spec
